{% set version = "0.6.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prophet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prophet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prophet/prophet_{{ version }}.tar.gz
  sha256: 61c2f9c11676f77896fea188d74acd28a9be0ce94769aac7c083848118816521

build:
  merge_build_host: true  # [win]
  skip: True  # [win and r_base == "4.0"]
  number: 2
  # given by the availability of rstan
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/libs/x64/prophet.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.66.0
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-stanheaders >=2.18.0
    - r-dplyr >=0.7.7
    - r-dygraphs >=1.1.1.4
    - r-extradistr
    - r-ggplot2
    - r-rlang >=0.3.0.1
    - r-rstan >=2.18.1
    - r-rstantools >=2.0.0
    - r-scales
    - r-tidyr >=0.6.1
    - r-xts
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bh >=1.66.0
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-stanheaders >=2.18.0
    - r-dplyr >=0.7.7
    - r-dygraphs >=1.1.1.4
    - r-extradistr
    - r-ggplot2
    - r-rlang >=0.3.0.1
    - r-rstan >=2.18.1
    - r-rstantools >=2.0.0
    - r-scales
    - r-tidyr >=0.6.1
    - r-xts

test:
  commands:
    - $R -e "library('prophet')"           # [not win]
    - "\"%R%\" -e \"library('prophet')\""  # [win]

about:
  home: https://github.com/facebook/prophet
  license: BSD_3_clause
  summary: Implements a procedure for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects. It works best with time series that have strong seasonal effects and several seasons of historical data. Prophet is robust to missing
    data and shifts in the trend, and typically handles outliers well.
  license_family: BSD
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
    - rluria14
    - ndmaxar
    - oblute
    - RyanHackney

# Package: prophet
# Title: Automatic Forecasting Procedure
# Version: 0.5
# Date: 2019-05-15
# Authors@R: c( person("Sean", "Taylor", email = "sjtz@pm.me", role = c("cre", "aut")), person("Ben", "Letham", email = "bletham@fb.com", role = "aut") )
# Description: Implements a procedure for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects. It works best with time series that have strong seasonal effects and several seasons of historical data. Prophet is robust to missing data and shifts in the trend, and typically handles outliers well.
# Depends: R (>= 3.2.3), Rcpp (>= 0.12.0), rlang (>= 0.3.0.1)
# Imports: dplyr (>= 0.7.7), dygraphs (>= 1.1.1.4), extraDistr, ggplot2, grid, rstan (>= 2.14.0), scales, stats, tidyr (>= 0.6.1), xts
# Suggests: knitr, testthat, readr
# License: BSD_3_clause + file LICENSE
# URL: https://github.com/facebook/prophet
# BugReports: https://github.com/facebook/prophet/issues
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# SystemRequirements: C++11
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-05-14 06:02:42 UTC; sjt
# Author: Sean Taylor [cre, aut], Ben Letham [aut]
# Maintainer: Sean Taylor <sjtz@pm.me>
# Repository: CRAN
# Date/Publication: 2019-05-14 21:50:03 UTC
